profiles/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'profiles'

urlpatterns = [
    path('', views.view_profile, name='view_profile'),
    path('edit/', views.edit_profile, name='edit_profile'),
    path('delete/', views.delete_profile, name='delete_profile'),  # URL для удаления профиля
    path('enrollments/', views.list_enrollments, name='list_enrollments'),  # URL для просмотра записей
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import register, login_view, logout_view

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('password_reset/', views.password_reset_request, name='password_reset'),
    path('edit_profile/', views.edit_profile, name='edit_profile')

]

webLearning/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import home
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls')),
    path('courses/', include('courses.urls')),
    path('profile/', include(('profiles.urls', 'profiles'), namespace='profiles')),  # Including profile app routes with namespace
    path('i18n/', include('django.conf.urls.i18n')),  # Adding the i18n URLs for language settings
]

urlpatterns += i18n_patterns(
    path('', home, name='home'),
)

templates/home.html
<!DOCTYPE html>
{% load i18n %} {% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% trans "Web Platform for Learning Programming" %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'main_styles.css' %}" />
  </head>
  <body>
    <div class="language-selector">
      <!-- <form method="post" action="{% url 'set_language' %}">
            {% csrf_token %}
            <select name="language" class="language-select" onchange="this.form.submit();">
                <option value="en" {% if LANGUAGE_CODE == 'en' %}selected{% endif %}>English</option>
                <option value="fr" {% if LANGUAGE_CODE == 'fr' %}selected{% endif %}>Français</option>
                <option value="sw" {% if LANGUAGE_CODE == 'sw' %}selected{% endif %}>Swahili</option>
                <option value="ar" {% if LANGUAGE_CODE == 'ar' %}selected{% endif %}>Arabic</option>
                <option value="af" {% if LANGUAGE_CODE == 'af' %}selected{% endif %}>Afrikaans</option>
                <option value="so" {% if LANGUAGE_CODE == 'so' %}selected{% endif %}>Somali</option>
                <option value="es" {% if LANGUAGE_CODE == 'es' %}selected{% endif %}>Spanish</option>
                <option value="ber" {% if LANGUAGE_CODE == 'ber' %}selected{% endif %}>Berber</option>
                <option value="pt" {% if LANGUAGE_CODE == 'pt' %}selected{% endif %}>Portuguese</option>
                <option value="nub" {% if LANGUAGE_CODE == 'nub' %}selected{% endif %}>Nubian</option>
            </select>
        </form> -->
    </div>

    <div class="container">
      <div class="profile-info">
        {% if request.user.is_authenticated %}
        <a href="{% url 'profiles:view_profile' %}">
          <div class="profile-icon">{{ request.user.username|slice:":1" }}</div>
        </a>
        <p class="welcome-msg">
          {% trans "Welcome, " %}{{ request.user.username }}!
        </p>
        <a href="/accounts/logout" class="logout-btn">{% trans "Logout" %}</a>
        {% endif %}
      </div>

      {% if not request.user.is_authenticated %}
      <div class="block">
        <h2>{% trans "Registration" %}</h2>
        <p>
          {% trans "Create an account to access all the features of our
          platform." %}
        </p>
        <a href="/accounts/register" class="btn">{% trans "Register" %}</a>
      </div>

      <div class="block">
        <h2>{% trans "Login" %}</h2>
        <p>{% trans "Already have an account? Log in here." %}</p>
        <a href="/accounts/login" class="btn">{% trans "Login" %}</a>
      </div>
      {% endif %}

      <h1>Welcome to our Web Platform for Learning Programming!</h1>

      <div class="block">
        <h2>{% trans "Courses" %}</h2>
        <p>{% trans "Explore our range of Programming language courses." %}</p>
        <a href="/courses" class="btn">{% trans "View Courses" %}</a>
      </div>

      <div class="block">
        <h2>{% trans "Lessons" %}</h2>
        <p>
          Access interactive lessons designed to help you learn Programming
          effectively.
        </p>
        <a href="{% url 'all_lessons_list' %}" class="btn"
          >{% trans "View Lessons" %}</a
        >
      </div>

      <div class="block">
        <h2>{% trans "Tests" %}</h2>
        <p>
          Test your knowledge of Programming language with our comprehensive
          tests.
        </p>
        <a href="{% url 'all_tests_list' %}" class="btn"
          >{% trans "View Tests" %}</a
        >
      </div>
    </div>
  </body>
</html>